config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # resources :dragao_bases
  # get "[o nome que queremos para a URL - Folder view]" => "[nome do Controller]#[nome do método/pagina]"

  get '/tamagoshis' => 'tamagoshi#start' # início
  get '/tamagoshis/new' => 'tamagoshi#new' # cadastro de um novo dragon
  post '/tamagoshis' => 'tamagoshi#create'

  get '/tamagoshis/play/:id' => 'tamagoshi#play', constraints: { id: /[0-9]+/ }, as: 'play' # ordem de chamada. chamar os metodos pra essa view:play.html.erb

  get '/tamagoshis/:id' => 'tamagoshi#show', constraints: { id: /[0-9]+/ }, as: 'exibicao' # colocando o prefix exibicao_path no controller

  get '/plays/:id/feed' => 'play#feed', constraints: { id: /[0-9]+/ } , as: 'comida'

  get '/plays/:id/rock' => 'play#rock', constraints: { id: /[0-9]+/ }, as: 'rock'

  get '/plays/:id/put_to_bed' => 'play#put_to_bed', constraints: { id: /[0-9]+/ }, as: 'put_to_bed'

  get '/plays/:id/toss' => 'play#toss', constraints: { id: /[0-9]+/ }, as: 'toss'

  get '/tamagoshis/index' => 'tamagoshi#index', as: 'exibe_todos'

  delete '/tamagoshis/:id' => 'tamagoshi#destroy', as: 'destroy'

end

app/models/dragon.rb
# frozen_string_literal: true

class Dragon
  attr_accessor :name, :owner_name, :stuff_in_intestine, :stuff_in_belly, :asleep
  def initialize(name, owner_name)
    @name = name
    @owner_name = owner_name
    @asleep = false
    @stuff_in_belly = 10 # He's full.
    @stuff_in_intestine = 0 # He does not need to go.
    puts "#{@name} is born."
  end

  def feed
    puts "You feed #{@name}."
    @stuff_in_belly = 10
    # Move food from belly to instestine.
    @stuff_in_belly -= 1
    @stuff_in_intestine += 1
    # Feed to much
    if @stuff_in_intestine >= 10
      @stuff_in_intestine = 0
      puts "Whoops! #{@name} had an accident..."
    end
  end

  def rock
    puts "You rock #{@name} gently."
    @asleep = true
    puts 'He briefly dozes off...'
    if @asleep
      @asleep = false
      puts '...but wakes when you stop.'
    end
  end

  def put_to_bed
    puts "You put #{@name} to bed."
    @asleep = true
    3.times do
      puts "#{@name} snores,filling the room with smoke.\n\n" if @asleep
    end

    if @asleep
      @asleep = false
      puts "#{@name} wakes up slowly."
      if @stuff_in_belly.zero?
        puts "Estou com fome..Vamos comer? \n Pressione 1 to feed me"
      end
    end
  end

  def toss
    puts "You toss #{@name} up into the air."
    # Toss with full intestine
    if @stuff_in_intestine >= 10
      @stuff_in_intestine = 0
      puts "Whoops! #{@name} had an accident..."
    end
  end
end

app/models/dragon_base.rb
# frozen_string_literal: true

class DragonBase < ActiveRecord::Base
  validates :name, presence: true
  validates :owner_name, presence: true
end

app/models/dragon_manager.rb
class Dragon_manager
  def initialize() #passar o dragon.
  end

  def menu
    puts
    puts '1- Feed'
    puts '2- walk'
    puts '3- Put to bed'
    puts '4- Rock'
    puts '5- Toss'
    puts '#- Pressione outras teclas para sair.'
    puts
  end

  def die(msg)
    puts msg
    exit
  end

  def recursivo(acao)
    case acao
    when "1"
      feed
      puts 'Estou cheinho..Preciso relaxar!'
      menu
      loop do
        puts 'Pressione 4 para que eu possa cochilar..'
        acao = gets.chomp
        break if (acao == "4")
      end
      recursivo(acao)
    when "2"
      walk
      menu
      puts 'Estou com cansado..Preciso de descanso!'
      loop do
        puts "Pressione 3 para descansarmos juntos!"
        acao = gets.chomp
        break if (acao == "3")
      end
      recursivo(acao)
    when "3"
      put_to_bed
      # puts "E agora o que iremos fazer #{@dono}?"
      puts menu
      acao = gets.chomp
      recursivo(acao)
    when "4"
      rock
      puts 'E agora o que iremos fazer ?'
      puts menu
      acao = gets.chomp
      recursivo(acao)
    when "5"
      toss
      puts "Me diverti muito com você #{@dono}"
      puts 'E agora o que iremos fazer ?'
      puts menu
      acao = gets.chomp
      recursivo(acao)
    else
      die("Your Baby Dragon is going away")
    end
  end
end

app/models/dragonmanager.rb
# frozen_string_literal: true

class DragonManager
  def initialize(dragon)
    @dragon = dragon
  end

  def menu
    puts
    puts '1- Feed'
    puts '2- walk'
    puts '3- Put to bed'
    puts '4- Rock'
    puts '5- Toss'
    puts '#- Pressione outras teclas para sair.'
    puts
  end

  def die(msg)
    puts msg
    exit
  end

  def recursivo(acao)
    case acao
    when '1'
      @dragon.feed
      puts 'Estou cheinho..Preciso relaxar!' # Criar metodos com as mensagens.
      menu
      loop do
        puts 'Pressione 4 para que eu possa cochilar..'
        acao = gets.chomp
        break if acao == '4'
      end
      recursivo(acao)
    when '2'
      @dragon.walk
      menu
      puts 'Estou com cansado..Preciso de descanso!'
      loop do
        puts 'Pressione 3 para descansarmos juntos!'
        @acao = gets.chomp
        break if acao == '3'
      end
      recursivo(acao)
    when '3'
      @dragon.put_to_bed
      # puts "E agora o que iremos fazer #{@dono}?"
      puts menu
      acao = gets.chomp
      recursivo(acao)
    when '4'
      @dragon.rock
      puts 'E agora o que iremos fazer ?'
      puts menu
      acao = gets.chomp
      recursivo(acao)
    when '5'
      @dragon.toss
      puts "Me diverti muito com você #{@dono}"
      puts 'E agora o que iremos fazer ?'
      puts menu
      acao = gets.chomp
      recursivo(acao)
    else
      die('Your Baby Dragon is going away')
    end
  end
end

app/models/tamagoshi.rb
# frozen_string_literal: true

class Tamagoshi < ActiveRecord::Base
  validates :name, presence: true
  validates :owner_name, presence: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/play_controller.rb
# frozen_string_literal: true

class PlayController < ActionController::Base
  before_filter :instance_manager

  def feed
    @manager.feed
    if @manager.feed
      flash[:notice] = "Your Baby Dragon has been feeded."
    else
      flash[:error] = "Your Baby Dragon hasn't been feeded."
    end
    redirect_to play_path(params[:id])
  end

  def rock
    @manager.rock
    if @manager.rock
      flash[:notice] = "Your Baby Dragon has been rocked."
    else
      flash[:error] = "Your Baby Dragon hasn't been rocked."
    end
    redirect_to play_path(params[:id])
  end

  def put_to_bed
    @manager.put_to_bed
    if @manager.put_to_bed
      flash[:notice] = "Your Baby Dragon has been put to bed."
    else
      flash[:error] = "Your Baby Dragon hasn't been put to bed."
    end
    redirect_to play_path(params[:id])
  end

  def toss
    @manager.toss
    if @manager.toss
      redirect_to play_path(params[:id])
      flash[:notice] = "Your Baby Dragon has been tossed."
    else
      flash[:error] = "Your Baby Dragon hasn't been tossed."
    end
    redirect_to play_path(params[:id])
  end

  private

  def instance_manager
    dragon = Tamagoshi.find(params[:id])
    @manager = Dragon.new(dragon.name, dragon.owner_name)
  end

end

app/controllers/tamagoshi_controller.rb
# frozen_string_literal: true

class TamagoshiController < ApplicationController

  def start
  end

  def new
    @dragon = Tamagoshi.new
  end

  def create
    @dragon = Tamagoshi.new(dragon_params)
    if @dragon.save
      redirect_to exibicao_path(@dragon.id)
    end
  end

  def show
    @dragon = Tamagoshi.find(params[:id]) # ou @dragon.id params[:id]
  end

  def index
    @dragons = Tamagoshi.all
  end

  def destroy
    @dragon = Tamagoshi.find(params[:id])

    if @dragon.present?
      @dragon.destroy
    end
    redirect_to exibe_todos_path
  end

  def play
    @dragon = Tamagoshi.find(params[:id])
  end

  private
  def dragon_params
    params.require(:tamagoshi).permit(:name, :owner_name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_message
    messages = ""
    [:notice, :info, :warning, :error].each {|type|
      if flash[type]
        messages += "<p class=\"#{type}\">#{flash[type]}</p>"
      end
    }
    messages
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DragonWeb</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tamagoshi/index.html.erb
<center><h1>Your Baby Dragons ... </h1> </center>

<% @dragons.each do |dragon| %>
<tr>
  <td><%= dragon.name %></td><p>
  <td><%= dragon.owner_name %></td></p>
  <td><%= link_to 'Destroy', destroy_path(dragon), method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>
<% end %>

app/views/tamagoshi/new.html.erb
<!-- quando der o submit, faz o create passar esse name e owner_name pro controller com params['hash']-->

<%=form_for @dragon do |f| %>
  Dragon Baby Name: <%= f.text_field :name %><br/>
  Your Name: <%= f.text_field :owner_name %><br/>
  <%= f.submit %>
<% end %>

<!-- Criar um link para a page play. -->

app/views/tamagoshi/play.html.erb
<!-- ETAPA DO JOGO -->
<p>
  What would you like to do with your Baby Dragon ?
</p>

<%= link_to "FEED", comida_path(@dragon) %>
<%= link_to "PUT TO BED", put_to_bed_path(@dragon) %>

<%= link_to "ROCK", rock_path(@dragon) %>

<%= link_to "TOSS", toss_path(@dragon) %>
<%= flash_message.html_safe %>

app/views/tamagoshi/show.html.erb
<center><h1>Your Baby Dragon ... </h1> </center>

  <p>
    <strong>Dragon Baby Name:</strong>
    <%= @dragon.name %>
  </p>

  <p>
    <strong>Your Name:</strong>
    <%= @dragon.owner_name %>
  </p>

  <%= link_to "START THE GAME", play_path %> <p>
  <%= link_to "SHOW ALL BABY DRAGONS", exibe_todos_path %>
</p>

app/views/tamagoshi/start.html.erb
<h1><center>WELCOME TO THE DRAGON BABY TAMAGOSHI WORLD</h1></center>

<!-- <a href="/tamagoshis/new"%>
  <img src="https://clashofclans.com/uploaded-images/_1440x900_crop_center-center_90/Baby_D.png?mtime=20160623143102">
</a> -->

<form method="get" action="/tamagoshis/new">
  <button type="submit">CREATE YOUR BABY DRAGON</button>
  <img src="https://clashofclans.com/uploaded-images/_1440x900_crop_center-center_90/Baby_D.png?mtime=20160623143102">
</form>